name: employee_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0 
  image_picker: ^0.8.5+3 
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  localstorage: ^4.0.0
  ffi: ^2.1.4
  get_storage: ^2.1.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  device_info_plus: ^11.4.0
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/kingfish-logo.webp

  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf
          weight: 700
